name: 'Run SonarCloud'
on:
  workflow_call:
    inputs:
      sonarProjectKey:  
        description: 'Project key'
        required: true
        type: string
      sonarProjectName:  
        description: 'project name'
        required: true
        type: string
      projectFile:  
        description: 'project file'
        required: false
        type: string
     
env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: SonarScanner for .NET 6 with pull request decoration support
      uses: highbyte/sonarscan-dotnet@v2.1.3
      with:
        sonarProjectKey: wetrainhub_${{ inputs.sonarProjectKey }} 
        sonarProjectName: ${{ inputs.sonarProjectName }}
        sonarOrganization: wetrainhub
        # Optional command arguments to dotnet test
        # Optional extra command arguments the the SonarScanner 'begin' command
        dotnetBuildArguments: ${{ inputs.projectFile }}
        #dotnetPreBuildCmd: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --configfile ./nuget.config --name github_pipeline --username ${{  secrets.DSSL_USERNAME }} --password ${{  secrets.DSSL_TOKEN }}  --store-password-in-clear-text
        dotnetTestArguments: ${{ inputs.projectFile }} --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"

